spring.application.name=spring-cloud-config-server
server.port=8888
#spring.cloud.config.server.git.default-label=microservices/git-config-repo/master
spring.cloud.config.server.git.uri=file:///D:/IdeaProjects/microservices-pj/git-localconfig-repo